version: "3.9"
services:
  ftp:
    image: shourai/vsftpd-alpine
    env_file: ./.prod.env
    volumes: 
      - /mnt/backup:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    container_name: ftp
    restart: always