version: "3.9"
services:
  ftp:
    image: bogem/ftp
    volumes: 
      - /mnt/backup:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    container_name: ftp
